In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('activitywatch_log.csv')
df.head(20)

,duration,app,title,url
0,0:00:01.149000,Code.exe,Visual Studio Code,NaN
1,0:00:01.028000,Code.exe,activitywatch_log.csv - Ai_companion - Visual ...,NaN
2,0:00:04.251000,Code.exe,test.py - Ai_companion - Visual Studio Code,NaN
3,0:00:00,Code.exe,● test.py - Ai_companion - Visual Studio Code,NaN
4,0:00:06.160000,Code.exe,test.py - Ai_companion - Visual Studio Code,NaN
5,0:00:04.364000,Code.exe,● test.py - Ai_companion - Visual Studio Code,NaN
6,0:00:12.477000,Code.exe,test.py - Ai_companion - Visual Studio Code,NaN
7,0:00:00,Code.exe,activitywatch_log.csv - Ai_companion - Visual ...,NaN
8,0:00:20.563000,Code.exe,● test.ipynb - Ai_companion - Visual Studio Code,NaN
9,0:00:18.701000,Code.exe,activitywatch_log.csv - Ai_companion - Visual ...,NaN
10,0:00:19.663000,Code.exe,test.py - Ai_companion - Visual Studio Code,NaN
11,0:00:01.036000,Code.exe,Visual Studio Code,NaN
12,0:00:14.484000,Code.exe,activitywatch_log.csv - Ai_companion - Visual ...,NaN
13,0:00:07.399000,Code.exe,test.py - Ai_companion - Visual Studio Code,NaN
14,0:00:12.629000,Code.exe,● test.py - Ai_companion - Visual Studio Code,NaN
15,0:00:05.131000,Code.exe,test.py - Ai_companion - Visual Studio Code,NaN
16,0:00:05.253000,Code.exe,● test.py - Ai_companion - Visual Studio Code,NaN
17,0:00:04.305000,Code.exe,test.py - Ai_companion - Visual Studio Code,NaN
18,0:00:00,Code.exe,activitywatch_log.csv - Ai_companion - Visual ...,NaN
19,0:00:22.959000,Code.exe,● test.ipynb - Ai_companion - Visual Studio Code,NaN

In [11]:
input_df = pd.read_csv("productivity_log.csv")

input_df.head(20)

,timestamp,app,title,mouse_clicks,keypresses,mouse_activity,typing_intensity,idle_time
0,2026-06-07 18:38:08,Code.exe,aw-watcher-input.spec - input_watcher - Visual...,2,0,1563.87,0,0:00:05.000822
1,2026-06-07 18:38:18,Code.exe,test.py - Ai_companion - Visual Studio Code,3,0,1440.70,0,0:00:05.000247
2,2026-06-07 18:38:28,Code.exe,productivity_log.csv - Ai_companion - Visual S...,0,0,257.82,0,0:00:04.995985
3,2026-06-07 18:38:38,Code.exe,productivity_log.csv - Ai_companion - Visual S...,1,0,0.00,0,0:00:05.000393
4,2026-06-07 18:38:48,Code.exe,test.py - Ai_companion - Visual Studio Code,0,0,152.59,0,0:00:05.000432
5,2026-06-07 18:38:58,Code.exe,test.py - Ai_companion - Visual Studio Code,1,6,196.66,0,0:00:05.000419
6,2026-06-07 18:39:08,Code.exe,test.py - Ai_companion - Visual Studio Code,2,0,1665.19,0,0:00:04.994512
7,2026-06-07 18:39:18,Code.exe,productivity_log.csv - Ai_companion - Visual S...,1,0,1356.99,0,0:00:05.001674
8,2026-06-07 18:39:31,Code.exe,productivity_log.csv - Ai_companion - Visual S...,2,2,1809.08,0,0:00:05.000230
9,2026-06-07 18:39:34,Code.exe,productivity_log.csv - Ai_companion - Visual S...,2,2,1809.08,0,0:00:05.000230
10,2026-06-07 18:39:37,Code.exe,test.py - Ai_companion - Visual Studio Code,2,2,1015.26,0,0:00:04.999669
11,2026-06-07 18:39:40,Code.exe,test.py - Ai_companion - Visual Studio Code,1,0,865.28,0,0:00:05.010575
12,2026-06-07 18:39:43,Code.exe,test.py - Ai_companion - Visual Studio Code,1,0,865.28,0,0:00:05.010575
13,2026-06-07 18:39:46,Code.exe,test.py - Ai_companion - Visual Studio Code,1,0,581.46,0,0:00:04.996281
14,2026-06-07 18:39:49,Code.exe,test.py - Ai_companion - Visual Studio Code,1,0,581.46,0,0:00:04.996281
15,2026-06-07 18:39:52,Code.exe,productivity_log.csv - Ai_companion - Visual S...,1,0,597.77,0,0:00:04.993028
16,2026-06-07 18:39:55,Code.exe,productivity_log.csv - Ai_companion - Visual S...,0,0,0.00,0,0:00:10.001059
17,2026-06-07 18:39:58,Code.exe,productivity_log.csv - Ai_companion - Visual S...,0,0,0.00,0,0:00:10.001059
18,2026-06-07 18:40:01,Code.exe,productivity_log.csv - Ai_companion - Visual S...,0,0,0.00,0,0:00:10.001059
19,2026-06-07 18:40:04,Code.exe,productivity_log.csv - Ai_companion - Visual S...,0,0,0.00,0,0:00:10.001059